### ISSUE TITLE
Links de navegación no funcionan

### ISSUE THREAD

**Issue by fabriziotonin** [MChanoM/ProyectoFinal#6]
Los liks de la barra de navegación del home no funcionan todos (actualidad, deporte, política, tecnología) redirigen a la pagina 404 
![image](https://user-images.githubusercontent.com/51201108/98726977-fc8a4d00-2375-11eb-9d46-d23c2b6ac11a.png)

**Comment by fabriziotonin** [comment]
Subir los cambios al Deploy

**Comment by aguirre739** [comment]
corregido y cambios subidos al deploy
